-- MySQL Script generated by MySQL Workbench
-- Thu Jul 24 21:15:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modelagemanimaisadocao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelagemanimaisadocao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelagemanimaisadocao` DEFAULT CHARACTER SET utf8 ;
USE `modelagemanimaisadocao` ;

-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `raca` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `fk_idusuario` INT NOT NULL,
  `fk_idstatus` INT NOT NULL,
  PRIMARY KEY (`idAnimal`, `fk_idusuario`, `fk_idstatus`),
  INDEX `fk_animal_usuario1_idx` (`fk_idusuario` ASC) VISIBLE,
  INDEX `fk_animal_status1_idx` (`fk_idstatus` ASC) VISIBLE,
  CONSTRAINT `fk_animal_usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_status1`
    FOREIGN KEY (`fk_idstatus`)
    REFERENCES `modelagemanimaisadocao`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `tipo_evento` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `fk_idusuario` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `fk_idusuario`),
  INDEX `fk_evento_usuario1_idx` (`fk_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_evento_usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`postagem` (
  `idcomunidade` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `comunidadecol` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `animal_idAnimal` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcomunidade`, `animal_idAnimal`, `usuario_idusuario`),
  INDEX `fk_postagem_animal1_idx` (`animal_idAnimal` ASC) VISIBLE,
  INDEX `fk_postagem_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_animal1`
    FOREIGN KEY (`animal_idAnimal`)
    REFERENCES `modelagemanimaisadocao`.`animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postagem_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`comentario` (
  `fk_idcomunidade` INT NOT NULL,
  `fk_idusuario` INT NOT NULL,
  `mensagem` VARCHAR(255) NOT NULL,
  `data` DATE NOT NULL,
  `id_comentario` INT NOT NULL,
  PRIMARY KEY (`fk_idcomunidade`, `fk_idusuario`, `id_comentario`),
  INDEX `fk_comunidade_has_usuario_usuario1_idx` (`fk_idusuario` ASC) VISIBLE,
  INDEX `fk_comunidade_has_usuario_comunidade1_idx` (`fk_idcomunidade` ASC) VISIBLE,
  CONSTRAINT `fk_comunidade_has_usuario_comunidade1`
    FOREIGN KEY (`fk_idcomunidade`)
    REFERENCES `modelagemanimaisadocao`.`postagem` (`idcomunidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comunidade_has_usuario_usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`midia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`midia` (
  `idmidia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tamanho` INT NOT NULL,
  `postagem_idcomunidade` INT NOT NULL,
  `postagem_animal_idAnimal` INT NOT NULL,
  `postagem_usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idmidia`, `postagem_idcomunidade`, `postagem_animal_idAnimal`, `postagem_usuario_idusuario`),
  INDEX `fk_midia_postagem1_idx` (`postagem_idcomunidade` ASC, `postagem_animal_idAnimal` ASC, `postagem_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_midia_postagem1`
    FOREIGN KEY (`postagem_idcomunidade` , `postagem_animal_idAnimal` , `postagem_usuario_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`postagem` (`idcomunidade` , `animal_idAnimal` , `usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
