-- MySQL Script generated by MySQL Workbench
-- Tue Jul 29 18:01:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema modelagemanimaisadocao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelagemanimaisadocao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelagemanimaisadocao` DEFAULT CHARACTER SET utf8mb3 ;
USE `modelagemanimaisadocao` ;

-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`tipo_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`tipo_animal` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`raca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`raca` (
  `idraca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fk_idtipo` INT NOT NULL,
  PRIMARY KEY (`idraca`),
  INDEX `fk_raca_tipo_idx` (`fk_idtipo` ASC) VISIBLE,
  CONSTRAINT `fk_raca_tipo`
    FOREIGN KEY (`fk_idtipo`)
    REFERENCES `modelagemanimaisadocao`.`tipo_animal` (`idtipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `raca` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_idraca` INT NOT NULL,
  `fk_idusuario` INT NOT NULL,
  `fk_idstatus` INT NOT NULL,
  PRIMARY KEY (`idAnimal`, `fk_idusuario`, `fk_idstatus`),
  INDEX `fk_animal_usuario1_idx` (`fk_idusuario` ASC) VISIBLE,
  INDEX `fk_animal_status1_idx` (`fk_idstatus` ASC) VISIBLE,
  INDEX `fk_animal_raca_idx` (`fk_idraca` ASC) VISIBLE,
  CONSTRAINT `fk_animal_raca`
    FOREIGN KEY (`fk_idraca`)
    REFERENCES `modelagemanimaisadocao`.`raca` (`idraca`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_animal_status1`
    FOREIGN KEY (`fk_idstatus`)
    REFERENCES `modelagemanimaisadocao`.`status` (`idstatus`),
  CONSTRAINT `fk_animal_usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`publicacao` (
  `idcomunidade` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `animal_idAnimal` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcomunidade`, `animal_idAnimal`, `usuario_idusuario`),
  INDEX `fk_postagem_animal1_idx` (`animal_idAnimal` ASC) VISIBLE,
  INDEX `fk_postagem_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_animal1`
    FOREIGN KEY (`animal_idAnimal`)
    REFERENCES `modelagemanimaisadocao`.`animal` (`idAnimal`),
  CONSTRAINT `fk_postagem_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`comentario` (
  `id_comentario` INT NOT NULL,
  `mensagem` VARCHAR(255) NOT NULL,
  `data` DATE NOT NULL,
  `fk_idcomunidade` INT NOT NULL,
  `fk_idusuario` INT NOT NULL,
  PRIMARY KEY (`id_comentario`, `fk_idcomunidade`, `fk_idusuario`),
  INDEX `fk_comunidade_has_usuario_usuario1_idx` (`fk_idusuario` ASC) VISIBLE,
  INDEX `fk_comunidade_has_usuario_comunidade1_idx` (`fk_idcomunidade` ASC) VISIBLE,
  CONSTRAINT `fk_comunidade_has_usuario_comunidade1`
    FOREIGN KEY (`fk_idcomunidade`)
    REFERENCES `modelagemanimaisadocao`.`publicacao` (`idcomunidade`),
  CONSTRAINT `fk_comunidade_has_usuario_usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo_evento` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `fk_idusuario` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `fk_idusuario`),
  INDEX `fk_evento_usuario1_idx` (`fk_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_evento_usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `modelagemanimaisadocao`.`midia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelagemanimaisadocao`.`midia` (
  `idmidia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tamanho` INT NOT NULL,
  `postagem_idcomunidade` INT NOT NULL,
  `postagem_animal_idAnimal` INT NOT NULL,
  `postagem_usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idmidia`, `postagem_idcomunidade`, `postagem_animal_idAnimal`, `postagem_usuario_idusuario`),
  INDEX `fk_midia_postagem1_idx` (`postagem_idcomunidade` ASC, `postagem_animal_idAnimal` ASC, `postagem_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_midia_postagem1`
    FOREIGN KEY (`postagem_idcomunidade` , `postagem_animal_idAnimal` , `postagem_usuario_idusuario`)
    REFERENCES `modelagemanimaisadocao`.`publicacao` (`idcomunidade` , `animal_idAnimal` , `usuario_idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
